import google.generativeai as genai
import streamlit as st
import os

# Need to add support for openai api as well as implement rate limiting

genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

# Function to validate whether the image is a human brain MRI scan
@st.cache_data
def validate_image(_image, file_name):
    chat_model = genai.GenerativeModel(model_name="gemini-1.5-flash")

    prompt = "Analyze the provided image and determine if it is a brain MRI scan. Return true if the image is a brain MRI scan and false if it is not."
    generation_config = genai.GenerationConfig(
        response_mime_type = "application/json",
        response_schema=bool
    )
    
    response = chat_model.generate_content(
        contents=[prompt, _image],
        generation_config=generation_config
    )

    response_text = response.text.strip().lower()
    print(response_text)

    return True if response.text.strip().lower() == "true" else False

# Function to interpret model results
@st.cache_data
def interpret_results(model_name, file_name, _saliency_map, _model_prediction, _confidence):
    prompt = f"""
    You are an expert neurologist. You are tasked with explaining a sliency map of a brain
    tumor MRI scan. The saliency map was generated by a deep learning model that was trained
    to classify brain tumors as either glioma, meningioma, pituitary, or no tumor. 

    The saliency map highlights the regions of the image that the machine learning model
    is focusing on to make the prediction.

    The deep learning model predicted the image to be of class '{_model_prediction}' with a 
    confidence of {_confidence * 100}.
    

    In your response:
    - Explain what regions of the brain the model is focusing on, based on the saliency map.
    Refer to the regions highlighted in light cyan, those are the regions where the model is 
    focusing on.
    - Explain possibly reasons why the model made the prediction it did.
    - !IMPORTANT! DO NOT MENTION ANYTHING LIKE 'The saliency map highlights the regions
    the model is focusing on, which are in light cyan'
    - !IMPORTANT! Keep your explanations to 4 sentences max.
    """

    chat_model = genai.GenerativeModel(model_name="gemini-1.5-flash")
    response = chat_model.generate_content([prompt, _saliency_map])

    return response.text